version: '3.8'
services:
  elasticsearch-search:
    healthcheck:
      test: curl -s http://elasticsearch:9200 >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 50
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.12
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - network-example
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false

  veridion-ds-app:
    build:
      context: .
    ports:
      - "8080:8080"
    networks:
      - network-example
    environment:
      - SPRING_BOOT_PROFILE=prod
    depends_on:
      elasticsearch:
        condition: service_healthy



networks:
  network-example:
    driver: bridge
