apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  labels:
    app: rabbitmq
spec:
  selector:
    app: rabbitmq # This ensures that the service sends traffic to Pods labeled with "app: rabbitmq".
  type: ClusterIP # Default type which makes the service only reachable within the cluster.
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
      name: amqp # Naming the port helps in identifying its purpose.
    - protocol: TCP
      port: 15672
      targetPort: 15672
      name: management # For the RabbitMQ management UI.
