#WITH DEBUGGING OPTION
apiVersion: apps/v1
kind: Deployment
metadata:
  name: veridionds-deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: veridionds
  template:
    metadata:
      labels:
        app: veridionds
    spec:
      containers:
        - name: veridionds
          image: veridionds:3.1.2
          ports:
            - containerPort: 8080
            - containerPort: 5005  # Debug port
          env:
            - name: SPRING_CONFIG_LOCATION
              value: /app/application.properties
